[package]
name = "sandsurf-machine"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
sandsurf-protocol = { path = "../sandsurf-protocol" }
serde.workspace = true
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_HostComputeSystem",
  "Win32_System_Memory",
] }
