[package]
name = "sandsurf-host"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
apple-source-check = ["sandsurf-machine/apple-source-check"]

[dependencies]
getrandom.workspace = true
cap-std = "=4.0.3"
libc.workspace = true
sandsurf-machine = { path = "../sandsurf-machine" }
sandsurf-native = { path = "../sandsurf-native" }
sandsurf-protocol = { path = "../sandsurf-protocol" }
sandsurf-state = { path = "../sandsurf-state" }
sandsurf-image = { path = "../sandsurf-image" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hmac.workspace = true
unicode-normalization.workspace = true
zeroize.workspace = true
reqwest.workspace = true
sandsurf-network = { path = "../sandsurf-network" }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Foundation", "Win32_System_Services"] }

[[bin]]
name = "sandsurf-host"
path = "src/main.rs"
