[package]
name = "sandsurf-guest"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "sandsurf-guest"
path = "src/main.rs"

[dependencies]
getrandom.workspace = true
futures.workspace = true
libc.workspace = true
netstack-smoltcp.workspace = true
sandsurf-protocol = { path = "../sandsurf-protocol" }
cap-std = "=4.0.3"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
